server:
  port: 8080

spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/ # this is the default already, change this if you have a different host or port

zuul:
  routes:
    todos:
      path: /api/todos/** # Forward /todos/** to the micro service todos-service with that same Path
      serviceId: todo-service
      stripPrefix: true # When forwarding the request strip the /api/todos prefix, this is already the default
      # url: http://localhost:8081/api/todos
    proxy:
      path: /proxy/**
      service-id: proxy-service
      strip-prefix: true
      # url: http://localhost:8082

# Enable Load Balancing for targeted micro services
ribbon:
  eureka:
    enabled: true


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_HOSTNAME:http://localhost:8761}/eureka/
    registry-fetch-interval-seconds: 5


logging:
  level:
    root: warn
    org.springframework: info
    com.melardev: trace
    org.springframework.cloud.netflix.zuul: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'