server:
  port: 8761

spring:
  sleuth:
    sampler:
      probability: 1

  application:
    name: discovery-service
  zipkin:
    base-url: http://localhost:9411/ #By default it is already set to local:9411 , but let's be explicit

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
